name: CI-CD
on: 
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2
      - name: Executar o Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Contrucao e Envio da Imagem docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            llem0s/fake-shop-desafio:v${{ github.run_number }}
            llem0s/fake-shop-desafio:latest
      
  CD: 
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      - uses: Azure/k8s-deploy@v5
        with:
           manifests: |
              k8s/deployment.yaml
           images: |
            llem0s/fake-shop-desafio:v${{ github.run_number }}'